//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGAI.DDU.Activities {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LGAI.DDU.Activities.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Analyze Document with DDU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AnalyzeDocument_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyze Document과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AnalyzeDocument_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApiKey for DDU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_APIKEY {
            get {
                return ResourceManager.GetString("DDU_APIKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApiKey for DDU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_APIKEY_Tip {
            get {
                return ResourceManager.GetString("DDU_APIKEY_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Endpoint과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_Endpoint {
            get {
                return ResourceManager.GetString("DDU_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Endpoint과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_Endpoint_Tip {
            get {
                return ResourceManager.GetString("DDU_Endpoint_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ErrorMessage {
            get {
                return ResourceManager.GetString("DDU_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ErrorMessage_Tip {
            get {
                return ResourceManager.GetString("DDU_ErrorMessage_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Chart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ExtractChart {
            get {
                return ResourceManager.GetString("DDU_ExtractChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Chart Flag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ExtractChart_Tip {
            get {
                return ResourceManager.GetString("DDU_ExtractChart_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Molecule 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ExtractMolecule {
            get {
                return ResourceManager.GetString("DDU_ExtractMolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Molecule Flag 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ExtractMolecule_Tip {
            get {
                return ResourceManager.GetString("DDU_ExtractMolecule_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Reaction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ExtractReaction {
            get {
                return ResourceManager.GetString("DDU_ExtractReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Reaction Flag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ExtractReaction_Tip {
            get {
                return ResourceManager.GetString("DDU_ExtractReaction_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ExtractTable {
            get {
                return ResourceManager.GetString("DDU_ExtractTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Table Flag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_ExtractTable_Tip {
            get {
                return ResourceManager.GetString("DDU_ExtractTable_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Document Resource과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_InputFIlePath {
            get {
                return ResourceManager.GetString("DDU_InputFIlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Document Resource과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_InputFIlePath_Tip {
            get {
                return ResourceManager.GetString("DDU_InputFIlePath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DDU Result 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_Result {
            get {
                return ResourceManager.GetString("DDU_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result from DDU 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDU_Result_Tip {
            get {
                return ResourceManager.GetString("DDU_Result_Tip", resourceCulture);
            }
        }
    }
}
